name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: curl -fsSL https://get.pnpm.io/install.sh | bash -
      - run: echo "/home/runner/.local/share/pnpm:$PATH" >> $GITHUB_PATH
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install sbt
        run: |
          curl -L -o sbt.tgz https://github.com/sbt/sbt/releases/download/v1.9.7/sbt-1.9.7.tgz
          sudo tar -xzf sbt.tgz -C /usr/local
          echo "/usr/local/sbt/bin" >> $GITHUB_PATH

      - name: Install
        run: make install

      - name: Compile backend
        run: sbt -Dsbt.supershell=false compile

      - name: Lint
        run: make lint

      - name: Test
        run: make test
