name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install pnpm
        run: curl -fsSL https://get.pnpm.io/install.sh | bash -
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
